main: net.thenamedev.legendarena.neverhaveiever.NeverHaveIEver
name: NeverHaveIEver
author: ThePixelDev
website: http://reddit.com/r/LegendArena
description: "§cNever Have I Ever minigame. §8Plugin source code: https://github.com/LegendArenaMC/NeverHaveIEver"