main: legendarena.NeverHaveIEver
name: NeverHaveIEver
author: ThePixelDev
depend: [LegendAPI]
website: http://thenamedev.net/legendarena/
description: "§cNever Have I Ever minigame. §8Plugin source code: https://github.com/LegendArenaMC/NeverHaveIEver"